"""MCP handler loader — importlib + mtime hot-reload + version injection.

Service ID format: "{category}/{service_name}"  (two-layer path)
Prod dir:  mcp-services/{category}/{service_name}/handler.py
Dev dir:   mcp-dev/{category}/{service_name}/handler.py
"""

from __future__ import annotations

import importlib.util
import json
import os
import time
import urllib.request
import urllib.error
from pathlib import Path
from typing import Any

MCP_SERVICES_DIR = Path(os.environ.get("MCP_SERVICES_DIR", "/app/data/mcp-services"))
MCP_DEV_DIR = Path(os.environ.get("MCP_DEV_DIR", "/app/data/mcp-dev"))
SYSTEM_MCP_DIR = Path(__file__).resolve().parent / "mcp_system"
_handler_cache: dict[str, tuple[float, Any]] = {}
# Cache for external MCP tools/list results: {service_id: (expiry_ts, tools_list)}
_external_tools_cache: dict[str, tuple[float, list[dict[str, Any]]]] = {}
_EXTERNAL_TOOLS_TTL = 300  # 5 minutes


def _handler_path(service_id: str) -> Path:
    """Handler path based on source prefix.

    system-*   → backend/services/mcp_system/{name}/handler.py
    internal   → /app/data/mcp-services/{mcp_path}/handler.py (from DB)
    """
    if service_id.startswith("system-"):
        name = service_id[len("system-"):]
        return SYSTEM_MCP_DIR / name / "handler.py"
    # Look up mcp_path from service record for correct directory mapping
    from infra import mcp_registry
    svc = mcp_registry.get_service(service_id)
    if svc:
        mcp_path = (svc.get("mcp_path") or "").strip("/")
        if mcp_path:
            return MCP_SERVICES_DIR / mcp_path / "handler.py"
    return MCP_SERVICES_DIR / service_id / "handler.py"


def _manifest_path(service_id: str) -> Path:
    """Manifest path based on source prefix."""
    if service_id.startswith("system-"):
        name = service_id[len("system-"):]
        return SYSTEM_MCP_DIR / name / "manifest.json"
    from infra import mcp_registry
    svc = mcp_registry.get_service(service_id)
    if svc:
        mcp_path = (svc.get("mcp_path") or "").strip("/")
        if mcp_path:
            return MCP_SERVICES_DIR / mcp_path / "manifest.json"
    return MCP_SERVICES_DIR / service_id / "manifest.json"


def _dev_handler_path(service_id: str) -> Path:
    """Dev handler path: mcp-dev/{category}/{service_name}/handler.py"""
    return MCP_DEV_DIR / service_id / "handler.py"


def _dev_manifest_path(service_id: str) -> Path:
    """Dev manifest path."""
    return MCP_DEV_DIR / service_id / "manifest.json"


def _load_version(manifest_path: str | Path) -> str:
    """Read version from manifest.json, default '0.0.0'."""
    try:
        raw = json.loads(Path(manifest_path).read_text(encoding="utf-8"))
        return str(raw.get("version", "0.0.0"))
    except Exception:
        return "0.0.0"


def _load_module_from_path(handler_path: Path, service_id: str) -> Any:
    """Import a handler.py from the given path."""
    import sys as _sys

    module_name = f"_mcp_handler_{service_id.replace('/', '_')}"
    spec = importlib.util.spec_from_file_location(module_name, str(handler_path))
    if spec is None or spec.loader is None:
        raise ImportError(f"cannot load handler: {service_id}")
    module = importlib.util.module_from_spec(spec)

    # Inject mcp_call for internal inter-MCP calls
    module.__dict__["mcp_call"] = _make_mcp_call()

    # Ensure handler's directory AND the shared MCP_SERVICES_DIR are on
    # sys.path so handler.py can import sibling helpers AND shared modules
    # like database.py / permissions.py (auto-generated by mcp_codegen).
    for _d in (str(handler_path.parent), str(MCP_SERVICES_DIR)):
        if _d not in _sys.path:
            _sys.path.insert(0, _d)

    spec.loader.exec_module(module)

    if not hasattr(module, "process") or not callable(module.process):
        raise ValueError(f"handler must define process(args, permissions): {service_id}")

    return module


def get_handler(service_id: str):
    """Load handler with source-aware routing, auto-reload on file change.

    system-*   → backend/services/mcp_system/{name}/handler.py
    internal   → /app/data/mcp-services/{service_id}/handler.py
    """
    path = _handler_path(service_id)
    if not path.is_file():
        raise FileNotFoundError(f"handler not found: {service_id}")

    mtime = path.stat().st_mtime
    cache_key = f"prod:{service_id}"

    if cache_key in _handler_cache:
        cached_mtime, module = _handler_cache[cache_key]
        if cached_mtime == mtime:
            return module

    module = _load_module_from_path(path, service_id)
    _handler_cache[cache_key] = (mtime, module)
    return module


def invoke_mcp(service_id: str, args: dict, permissions: dict, *, tool_name: str = "") -> dict[str, Any]:
    """Prod invoke: handler.process(args, permissions) → wrapped {ok, data, error, version}.

    For source='external', routes to HTTP JSON-RPC proxy.
    """
    # ── Resolve source ────────────────────────────────────────────
    from infra import mcp_registry as _reg
    svc = _reg.get_service(service_id)
    source = svc.get("source", "") if svc else ""

    if source == "external" and svc:
        # Determine the original tool name for the remote MCP server
        remote_tool = _resolve_external_tool_name(service_id, tool_name)
        return _invoke_external(service_id, svc, remote_tool, args)

    # ── Internal / System path ────────────────────────────────────
    try:
        handler = get_handler(service_id)
        result = handler.process(args, permissions)
        version = _load_version(_manifest_path(service_id))
        return {"ok": True, "data": result, "error": None, "version": version}
    except Exception as exc:
        return {"ok": False, "data": None, "error": str(exc), "version": "0.0.0"}


def _resolve_external_tool_name(service_id: str, tool_name: str) -> str:
    """Given an agent-side tool_name like 'svc_id__original_tool', return the
    remote MCP server's tool name. Falls back to service_id if tool_name is empty
    or doesn't contain the separator.
    """
    if not tool_name:
        return ""
    safe_sid = service_id.replace("-", "_")
    if tool_name == safe_sid:
        # Legacy / no tool name specified — pass empty (server may have defaults)
        return ""
    prefix = f"{safe_sid}__"
    if tool_name.startswith(prefix):
        return tool_name[len(prefix):]
    # tool_name doesn't match the expected prefix pattern — pass as-is
    return tool_name


# ── External MCP HTTP proxy ────────────────────────────────────────

def _parse_sse_json(raw_text: str) -> dict[str, Any]:
    """Parse SSE (Server-Sent Events) text and extract the first 'data:' JSON payload.

    Some MCP servers use SSE streaming::

        event: message
        data: {"jsonrpc":"2.0",...}

    This extracts and parses the data line.
    """
    for line in raw_text.splitlines():
        line = line.strip()
        if line.startswith("data:"):
            payload = line[5:].strip()
            if payload:
                return json.loads(payload)
    # Fallback: try parsing the whole text as JSON
    return json.loads(raw_text)


def _mcp_jsonrpc_post(endpoint: str, payload: dict, timeout: int = 60) -> dict[str, Any]:
    """POST a JSON-RPC payload to an MCP server, handling SSE responses."""
    data_bytes = json.dumps(payload, ensure_ascii=False).encode("utf-8")
    req = urllib.request.Request(
        endpoint,
        data=data_bytes,
        headers={
            "Content-Type": "application/json",
            "Accept": "application/json, text/event-stream",
        },
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        raw = resp.read().decode("utf-8")
    return _parse_sse_json(raw)


def _invoke_external(service_id: str, svc: dict, remote_tool: str, args: dict) -> dict[str, Any]:
    """Call an external MCP server via HTTP JSON-RPC tools/call."""
    endpoint = (svc.get("endpoint_url") or "").strip()
    if not endpoint:
        return {"ok": False, "data": None, "error": "endpoint_url is empty"}

    payload: dict[str, Any] = {
        "jsonrpc": "2.0",
        "id": 1,
        "method": "tools/call",
        "params": {
            "name": remote_tool,
            "arguments": args,
        },
    }

    try:
        result = _mcp_jsonrpc_post(endpoint, payload, timeout=60)
    except urllib.error.HTTPError as e:
        body = ""
        try:
            body = e.read().decode("utf-8", errors="replace")[:500]
        except Exception:
            pass
        return {"ok": False, "data": None, "error": f"HTTP {e.code}: {body or e.reason}"}
    except urllib.error.URLError as e:
        return {"ok": False, "data": None, "error": f"Connection error: {e.reason}"}
    except Exception as exc:
        return {"ok": False, "data": None, "error": str(exc)}

    # ── Parse JSON-RPC response ───────────────────────────────────
    if "error" in result:
        err = result["error"]
        err_msg = err.get("message", str(err)) if isinstance(err, dict) else str(err)
        return {"ok": False, "data": None, "error": err_msg}

    rpc_result = result.get("result", {})
    content = rpc_result.get("content", []) if isinstance(rpc_result, dict) else []

    # ── Handle tools/call isError (MCP spec) ──────────────────────
    if isinstance(rpc_result, dict) and rpc_result.get("isError"):
        err_text = ""
        for item in content:
            if isinstance(item, dict) and item.get("type") == "text":
                err_text = str(item.get("text", ""))
                break
        return {"ok": False, "data": None, "error": err_text or "Remote tool error"}

    # MCP returns content as [{type: "text", text: "..."}]
    text_parts: list[str] = []
    parsed_data: Any = None
    for item in content:
        if not isinstance(item, dict):
            continue
        if item.get("type") == "text":
            text = str(item.get("text", ""))
            try:
                parsed = json.loads(text)
                if parsed_data is None:
                    parsed_data = parsed
                else:
                    text_parts.append(text)
            except (json.JSONDecodeError, TypeError):
                text_parts.append(text)

    if parsed_data is not None:
        return {"ok": True, "data": parsed_data, "error": None}
    if text_parts:
        return {"ok": True, "data": "\n".join(text_parts), "error": None}
    # Fallback: return raw result
    return {"ok": True, "data": rpc_result, "error": None}


def fetch_external_tools(service_id: str) -> list[dict[str, Any]]:
    """Call the external MCP server's tools/list and return tools in evotown format.

    Each tool dict: {name, description, input_schema}
    Tool name format: {service_safe_id}__{original_tool_name}

    Results are cached for _EXTERNAL_TOOLS_TTL seconds.
    """
    from infra import mcp_registry as _reg
    svc = _reg.get_service(service_id)
    if not svc or svc.get("source") != "external":
        return []
    if svc.get("status") != "online":
        return []

    # Check cache
    now = time.time()
    if service_id in _external_tools_cache:
        expiry, cached = _external_tools_cache[service_id]
        if now < expiry:
            return cached

    endpoint = (svc.get("endpoint_url") or "").strip()
    if not endpoint:
        return []

    try:
        payload = {"jsonrpc": "2.0", "id": 1, "method": "tools/list", "params": {}}
        result = _mcp_jsonrpc_post(endpoint, payload, timeout=30)
    except Exception:
        # On failure, return empty; tools won't be available until cache expires
        return []

    if "error" in result:
        return []

    rpc_result = result.get("result", {})
    remote_tools = rpc_result.get("tools", []) if isinstance(rpc_result, dict) else []

    safe_sid = service_id.replace("-", "_")
    tools: list[dict[str, Any]] = []
    for rt in remote_tools:
        if not isinstance(rt, dict):
            continue
        original_name = rt.get("name", "")
        if not original_name:
            continue
        tools.append({
            "name": f"{safe_sid}__{original_name}",
            "description": rt.get("description") or original_name,
            "input_schema": rt.get("inputSchema") or rt.get("input_schema") or {"type": "object", "properties": {}},
        })

    # Cache
    _external_tools_cache[service_id] = (now + _EXTERNAL_TOOLS_TTL, tools)
    return tools


def invoke_mcp_dev(service_id: str, args: dict, permissions: dict) -> dict[str, Any]:
    """Dev invoke: load from mcp-dev/{category}/{name}/handler.py."""

    handler_path = _dev_handler_path(service_id)
    if not handler_path.is_file():
        return {"ok": False, "data": None, "error": f"dev handler not found: {handler_path}", "version": "0.0.0"}

    try:
        module = _load_module_from_path(handler_path, f"dev:{service_id}")
        result = module.process(args, permissions)
        version = _load_version(_dev_manifest_path(service_id))
        return {"ok": True, "data": result, "error": None, "version": version}
    except Exception as exc:
        return {"ok": False, "data": None, "error": str(exc), "version": "0.0.0"}


mcp_dev_call = invoke_mcp_dev


def _make_mcp_call():
    """Closure for internal inter-MCP calls (prod only)."""

    def mcp_call(service_id: str, args: dict) -> Any:
        handler = get_handler(service_id)
        return handler.process(args, {})

    return mcp_call


def clear_handler_cache(service_id: str | None = None):
    """Clear cache for a specific handler or all handlers."""
    global _handler_cache, _external_tools_cache
    if service_id:
        _handler_cache.pop(f"prod:{service_id}", None)
        _external_tools_cache.pop(service_id, None)
    else:
        _handler_cache.clear()
        _external_tools_cache.clear()
